### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Eternity-Sky** [ouyangyipeng/XiaoyuanKousuan#1]
PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.

**Comment by Eternity-Sky** [comment]
把？识别成7

**Comment by Eternity-Sky** [comment]
[请参考](https://github.com/Eternity-Sky/XiaoYuanKouSuan_Auto/blob/main/%E5%B0%8F%E7%8C%BF%E6%90%9C%E9%A2%98.py)

**Comment by ouyangyipeng** [comment]
厉害厉害，我这个写的很随便，如果大佬愿意的话可以帮我改一点点~这个？的问题出现的不稳定，我也不知道该怎么解决来着

**Comment by Eternity-Sky** [comment]
嗯，会考虑新建拉取，谢谢

**Comment by Eternity-Sky** [comment]
https://github.com/ouyangyipeng/XiaoyuanKousuan/pull/2

**Comment by ouyangyipeng** [comment]
感谢优化，之前写了这个之后一直忙着没时间做，现在有大佬来优化了非常开心
